FROM python:3.7-buster

ENV ACCEPT_EULA=Y

# Microsoft SQL Server Prerequisites
RUN apt-get update \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get update \
    && apt-get -y --no-install-recommends install \
        unixodbc-dev \
        unixodbc \
        msodbcsql17

COPY . /app
WORKDIR /app
RUN ls 
RUN pip install --upgrade pip
RUN  pip install  -r requirements.txt
EXPOSE 5000
EXPOSE 80

CMD python ./__init__.py



